### ISSUE TITLE
refill upgrade deletes items when backpack and inventory is full

### ISSUE THREAD

**Issue by Buungle** [Salandora/SophisticatedBackpacks#38] opened 2024-07-22 06:17 UTC
when i use the refill upgrade middle click the item thats switched out is deleted

steps to reproduce

1. fill backpack with items + refill upgrade
2. fill inventory with items
3. middle click/select block that is in the backpack
4. the item in hand is replaced with the item in the backpack and the item in your hand previously is deleted

using the latest version of the mod on fabric 1.20.1

**Comment by Salandora** [comment] 2024-07-22 15:44
Duplicate of #32

**Closed as completed by Salandora** 2024-07-22 15:44 UTC
