### ISSUE TITLE
Conflicting default methods crash

### ISSUE THREAD

**Issue by Demadunk** [Salandora/SophisticatedBackpacks#67] opened 2024-11-15 17:31 UTC
Conflicting default method between porting lib and sophisticated core lib

First crash was when attempting to enter a world
https://bytebin.lucko.me/0TiurZ7MCD

second crash was after I reloaded game and entered a world successfully to then have a crash.
https://bytebin.lucko.me/t8kr9JvzZo

Crash happens on loading a world or attempting to load a world, whichever happens first.

Version 1.21.1 newest version

**Comment by Salandora** [comment] 2024-11-15 22:12
Duplicate of #65

**Closed as completed by Salandora** 2024-11-15 22:12 UTC
