### ISSUE TITLE
Config FIle is reset when the server is started, rendering changes impossible.

### ISSUE THREAD

**Issue by TacocaTYT** [Salandora/SophisticatedBackpacks#31] opened 2024-07-02 11:23 UTC
**Describe the bug**
Config FIles get reset when we restart our server, making it impossible to configure the mod

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. make a server
2. edit configs
3. start server
4. config file is reset to default values

**Expected behavior**
config file remains as set, in game configuration reflects changes dictated by user (ie slot coutn changes, etc)

**Screenshots**

**Versions**
1.20.1 2.19.5 build 104

**Comment by Salandora** [comment] 2024-07-02 14:58
When you make changes to the config is the server running?

**Comment by TacocaTYT** [comment] 2024-07-04 06:15
no, the server is offlien when we are making changes

**Comment by Salandora** [comment] 2024-07-04 11:17
Can you make the changes and upload the file here.
I'll try to investigate what is happening then.

**Comment by TacocaTYT** [comment] 2024-07-14 22:28
i can grab a config file in a moment sure, but the main issue is that the configs are always hard reset on launch

**Comment by TacocaTYT** [comment] 2024-07-14 22:34
[sophisticatedbackpacks-server.txt](https://github.com/user-attachments/files/16228993/sophisticatedbackpacks-server.txt)

**Comment by Salandora** [comment] 2024-09-16 19:04
I'm unable to repeat this problem.
The config never gets reset for me.

Also one more question, after making the changes and starting the server, did you create new backpacks, because the old backpacks will not change the amount of slots only new ones will.

**Comment by Salandora** [comment] 2024-10-12 14:48
Closing cause, not reproducible and new versions out.

**Closed as completed by Salandora** 2024-10-12 14:48 UTC
Labels: not reproduceable
