### ISSUE TITLE
The problem with binds

### ISSUE THREAD

**Issue by Gumba005** [Salandora/SophisticatedBackpacks#36] opened 2024-07-20 10:11 UTC
I want the backpack to open with the right mouse button and not with B because it's more convenient, **but** when I'm wearing armor, the backpack is put on instead of opening.How can this be fixed?

**Comment by Salandora** [comment] 2024-07-21 15:15
With the right mouse button?
Did you rebind the use key too or are you producing a keybind conflict?

**Comment by ghost** [comment] 2024-07-28 08:17
I have the same issue. Since a few versions of minecraft there is the feature that you can swap armor in the hotbar with the one you are wearing. The problem is that this is also the case with the backpacks. But only if you are already wearing a chest plate. if the upper body slot is empty, you can also open the backpacks by right-clicking it in the hotbar.

**Comment by Salandora** [comment] 2024-07-29 11:12
So did any of you rebind the key to the right click or not?
I need more information because it works just normal for me. I'm not equiping the backpack when right clicking. 

Please provide step by step instructions to reproduce the issue.

**Comment by ghost** [comment] 2024-07-30 18:15
![Screenshot (20)](https://github.com/user-attachments/assets/918021d1-79f9-441b-8910-14e00c84e03e)
![Screenshot (21)](https://github.com/user-attachments/assets/edc5b5ea-afdd-4fd4-aa00-090d709f6693)
these are my keybinds for the backpack an the right mouse button. I use a modpack that I created to play on a server with friends. There are also the travelers backpack mod and trinkets installed. the modpack is on 1.20.1 an we are using fabric 0.15.11

**Comment by Salandora** [comment] 2024-09-16 19:06
Tested this for a while now, was never able to reproduce the problem. 
Could be an incompatibility with another mod.

**Comment by Salandora** [comment] 2024-10-12 14:48
Closing cause, not reproducible and new versions out.

**Closed as completed by Salandora** 2024-10-12 14:48 UTC
Labels: not reproduceable
