### ISSUE TITLE
Anvil Upgrade Crash

### ISSUE THREAD

**Issue by Xechorizo** [Salandora/SophisticatedBackpacks#11] opened 2024-05-15 17:38 UTC
**Describe the bug**
- The main screen of the backpack crashes the client if there is anything inside the Anvil upgrade's inventory slots and the backpack is closed or the settings are opened and closed.
Crash log if it's a crash.
- https://paste.atlauncher.com/view/bc3c9f0e-b64f-4e6d-ba68-a03e647b8dda
Info on what other mods you're using that may cause a conflict here if applicable.
- Created a dedicated Minecraft v1.20.1 Fabric v0.15.11 instance to replicate this.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack (any tier)
2. Ensure Anvil upgrade is slotted
3. Put any item in first Anvil inventory slot
4. Close backpack OR open settings screen
5. Open backpack OR close settings screen
6. Client crashes

**Expected behavior**
Backpack opens normally, either with items within the Anvil upgrade inventory slots still, or moved out to the player or backpack inventory.

**Screenshots**

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases.
 - fabric-api-0.92.1+1.20.1.jar
 - ModernKeyBinding-Fabric-1.20-1.2.1.jar
 - sophisticatedbackpacks-3.19.4+mc1.20.1-SNAPSHOT-build.39.jar
 - sophisticatedcore-0.5.108+mc1.20.1-SNAPSHOT-build.39.jar

**Comment by Salandora** [comment] 2024-05-15 19:48
Duplicate of #6 
Fix will be included in next release.

**Closed as completed by Salandora** 2024-05-15 19:48 UTC
